config/routes.rb
QuieroAprender::Application.routes.draw do
  
  resources :welcome
    
  resources :user_sessions
    match 'login' => "user_sessions#new",  :as => :login, via: [:get, :post]
    match 'logout' => "user_sessions#destroy", :as => :logout, via: [:get, :post]

  resources :user_facebook_sessions
    match 'fb_login' => "user_facebook_sessions#login", :as => :fb_login, via: [:get, :post]
    match 'fb_authorization' => "user_facebook_sessions#authorization", :as => :fb_authorization, via: [:get, :post]
    match 'fb_authorization_callback' => "user_facebook_sessions#authorization_callback", :as => :fb_authorization_callbak, via: [:get, :post]
    match 'fb_publish_wall_post' => "user_facebook_sessions#publish_wall_post", :as => :fb_publish_wall_post, via: [:get, :post]
    match 'fb_logout' => "user_facebook_sessions#logout", :as => :fb_logout, via: [:get, :post]
    
  resources :users  # give us our some normal resource routes for users
    match 'signup' => 'users#new', :as => :signup, via: [:get, :post]
    match '/users/edit/:id' => 'users#edit', :as => :update, via: [:get, :post]
    match 'createTeacher' => 'users#create_teacher', :as => :create_teacher, via: [:get, :post]
    match 'newTeacher' => 'users#new_teacher', :as => :new_teacher, via: [:get, :post]
  
  resources :plans
    match 'plans' => "plans#index", :as => :plans_index, via: [:get, :post]
    match 'plans/:id' => "plans#show", :as => :plans_show, via: [:get, :post]
  
  resources :teachers
    match 'home' => "welcome#index", :as => :home, via: [:get, :post]
  
  get '/update_subcategories' => "welcome#update_subcategories", as: 'update_subcategories'

  get '/decode_address' => "welcome#decode_address", as: 'decode_address'
  get '/courses/update_subcategories_courses' , as: 'update_subcategories_courses'
  get '/courses/enroll/:id', to: 'courses#enroll', as: 'enroll_course'
  get '/uploads/:id', to: 'uploads#index', as: 'upload'
  resources :courses do
    resources :opinions, :only => [:create]
    resources :consultations, :only => [:create]
    resources :uploads, :only => [:create]
  end
  resources :advertisings
  resources :students
  

  root :to => "welcome#index"

end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
	has_and_belongs_to_many :tags
end

app/controllers/advertisings_controller.rb
class AdvertisingsController < ApplicationController
	authorize_resource 
	before_action :set_advertising, only: [:show, :edit, :update, :destroy]

  # GET /advertisings
  # GET /advertisings.json
  def index
    @advertisings = Advertising.all
  end

  # GET /advertisings/1
  # GET /advertisings/1.json
  def show
   @advertising = Advertising.find(params[:id])
  end

  # GET /advertisings/new
  def new
    @advertising = Advertising.new
    @posibleTags=Tag.all.map{|a| a.name}
    @selectedTags=[]
  end

  # GET /advertisings/1/edit
  def edit
    @advertising = Advertising.find(params[:id])
  end

  # POST /advertisings
  # POST /advertisings.json
  def create
    @advertising = Advertising.new(advertising_params)
    setTags(@advertising)
    respond_to do |format|
      if @advertising.save
        format.html { redirect_to @advertising, notice: 'Advertising was successfully created.' }
        format.json { render action: 'show', status: :created, location: @advertising }
      else
        format.html { render action: 'new' }
        format.json { render json: @advertising.errors, status: :unprocessable_entity }
      end
    end
  end
  def setTags(advertising)
    params[:selectedTags].gsub!(/\s/,'')
      tags = params[:selectedTags].split(',')
      tags.each do |t|
          tag = Tag.find_by_name(t)
          @advertising.tags << tag
      end 
  end

  # PATCH/PUT /advertisings/1
  # PATCH/PUT /advertisings/1.json
  def update
    @advertising = Advertising.find(params[:id])
    respond_to do |format|
      if @advertising.update(advertising_params)
        format.html { redirect_to @advertising, notice: 'advertising was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @advertising.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisings/1
  # DELETE /advertisings/1.json
  def destroy
    @advertising = Advertising.find(params[:id])
    @advertising.destroy
    respond_to do |format|
      format.html { redirect_to advertisings_url }
      format.json { head :no_content }
    end
  end

  private
   # Use callbacks to share common setup or constraints between actions.
    def set_advertising
 #     @advertising = advertising.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertising_params
      params.require(:advertising).permit(:name, :description, :address, :price, :tags, :image)
    end
end

app/views/advertisings/_form.html.erb
<%= bootstrap_form_for(@advertising) do |f| %>
  <% if @advertising.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertising.errors.count, "error") %> prohibited this advertising from being saved:</h2>

      <ul>
      <% @advertising.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row ">
    <div class="col-md-4 ">  
      <div class="field" >
         <%= f.text_field :name, :label => "Nombre", :placeholder => "Nombre" %>
      </div>
    </div>
  </div> 
  <br>
  <div class="row">
    <div class="col-md-4 ">     
      <div class="field">
        <%= f.text_area :description, :label => "Descripción", :placeholder => "Descripción" %>
      </div>
    </div>
    <div class="col-md-4">  
      <%= f.text_field :address, :label => "Dirección", :placeholder => "Dirección" ,:class => "required" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">  
      <%= f.text_field :price, :label => "Precio", :placeholder => "Precio" ,:class => "required" %>
    </div>
    <div class="col-md-4">
      <p class="control-label">Tags</p>
      <input type="text" class="form-control" id="tokenfield" name="selectedTags" value="" />
    </div>
  </div>

  <hr>
  <hr>
  <div class="col-md-4">
    <button type="submit" class="btn btn-primary">Crear</button>
  
<% end %>

app/views/advertisings/edit.html.erb
<h3><%= @advertising.name %> </h3>

<hr>
<%= render 'form' %>

<%= link_to 'Show', @advertising %> |
<%= link_to 'Back', advertisings_path %>
<hr>

app/views/advertisings/index.html.erb
<h1>Publicidades</h1>

<hr>
<table class="table table-bordered table-hover table-condensed">
  <thead class="advertisingList">
    <tr>
      <th>Nombre </th>
      <th>Descripción </th>
      <th>Dirección </th>
      <th>Precio </th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @advertisings.each do |advertising| %>
      <tr>
        <td><%= advertising.name %></td>
        <td><%= advertising.description %></td>
        <td><%= advertising.address %></td>
        <td><%= advertising.price %></td>
        <td>
          <%= button_to advertising , class: "btn btn-primary btn-xs", :method => :get do %>
            <span class="glyphicon glyphicon-search "></span>
          <% end %>
          <%= button_to edit_advertising_path(advertising) , class: "btn btn-primary btn-xs", :method => :get do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= button_to advertising ,class: "btn btn-danger btn-xs", method: :delete, data: {confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Nueva publicidad', new_advertising_path , class: "btn btn-primary", :method => :get %>
<hr>

app/views/advertisings/new.html.erb
<h1>Crear publicidad</h1>

<hr>

<%= render 'form' %>

<%= button_to 'Volver',advertisings_path , class: "btn btn-primary" , :method => :get %>
</div>

<hr>

<script type="text/javascript" >
	
	$('#tokenfield').tokenfield({
			  autocomplete: {
			    source: <%= raw @posibleTags %>,
			    delay: 100
			  },
			  showAutocompleteOnFocus: true
	});
</script>


<%= javascript_tag do %>
var addressPicker = new AddressPicker();
$('#advertising_address').typeahead(null, {
  displayKey: 'description',
  source: addressPicker.ttAdapter()
});
 
$(addressPicker).on('addresspicker:selected', function (event, result) {
  $('#your_lat_input').val(result.lat());
  $('#your_lng_input').val(result.lng());
  $('#your_city_input').val(result.nameForType('locality'));
});

<% end %>

app/views/advertisings/show.html.erb
<!-- Toque algo en bootstrap que hace que se vean feas las estrellas, asi que lo incluyo
de vuelta para que se vean lindas pisando la config que toque arriba :P 
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
-->
<hr>
<div class="row">
  <div class="col-md-5">
     <%= image_tag @advertising.image , :size=>"300x300" %></a>  
  </div>
  <div class="col-md-6">
   
      <h1><%= @advertising.name %></h1>
      <hr>

      <p>
        <b>Descripción:</b> <%= @advertising.description %>
      </p>
      <p>
        <b>Dirección:</b> <%= @advertising.address %>
      </p>
      <p> <b>Precio:</b>
      <span class="glyphicon glyphicon-usd"></span> <%= @advertising.price %> </p>
       <br><br> 
      <button type="button" class="btn btn-success">Consultar</button>
 </div>
     
</div>


<%= javascript_tag do %>
<% end %>