config/routes.rb
QuieroAprender::Application.routes.draw do
  
  resources :welcome
    
  resources :user_sessions
    match 'login' => "user_sessions#new",  :as => :login, via: [:get, :post]
    match 'logout' => "user_sessions#destroy", :as => :logout, via: [:get, :post]

  resources :user_facebook_sessions
    match 'fb_login' => "user_facebook_sessions#login", :as => :fb_login, via: [:get, :post]
    match 'fb_authorization' => "user_facebook_sessions#authorization", :as => :fb_authorization, via: [:get, :post]
    match 'fb_authorization_callback' => "user_facebook_sessions#authorization_callback", :as => :fb_authorization_callbak, via: [:get, :post]
    match 'fb_publish_wall_post' => "user_facebook_sessions#publish_wall_post", :as => :fb_publish_wall_post, via: [:get, :post]
    match 'fb_logout' => "user_facebook_sessions#logout", :as => :fb_logout, via: [:get, :post]
    
  resources :users  # give us our some normal resource routes for users
    match 'signup' => 'users#new', :as => :signup, via: [:get, :post]
    match '/users/edit/:id' => 'users#edit', :as => :update, via: [:get, :post]
    match 'createTeacher' => 'users#create_teacher', :as => :create_teacher, via: [:get, :post]
    match 'newTeacher' => 'users#new_teacher', :as => :new_teacher, via: [:get, :post]
  
  resources :plans
    match 'plans' => "plans#index", :as => :plans_index, via: [:get, :post]
    match 'plans/:id' => "plans#show", :as => :plans_show, via: [:get, :post]
  
  resources :teachers
    match 'home' => "welcome#index", :as => :home, via: [:get, :post]
  
  get '/update_subcategories' => "welcome#update_subcategories", as: 'update_subcategories'

  get '/decode_address' => "welcome#decode_address", as: 'decode_address'
  get '/courses/update_subcategories_courses' , as: 'update_subcategories_courses'
  get '/courses/enroll/:id', to: 'courses#enroll', as: 'enroll_course'
  get '/uploads/:id', to: 'uploads#index', as: 'upload'
  resources :courses do
    resources :opinions, :only => [:create]
    resources :consultations, :only => [:create]
    resources :uploads, :only => [:create]
  end
  resources :advertisings
  resources :students
  

  root :to => "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base
	
	validates :email, presence: true, uniqueness: true
  validates :password, presence: true, :on => :create
  validates :password_confirmation, presence: true, :on => :create
  validates :name, presence: true, :on => :create
	
	acts_as_authentic do |c|
    c.login_field = 'email'
    c.logged_in_timeout = 30*60 # default is 10 minutes
  end # block optional
  
  ROLES = [ROLE_STUDENT = 5, ROLE_TEACHER = 10, ROLE_ADMIN = 20]

  validates :role, inclusion: {in: ROLES}

  after_initialize :default_values
  after_create :create_role
  
  attr_accessor :role_desc
 
  def role_desc
    case role
    when User::ROLE_STUDENT
      role_desc = 'Estudiante'
    when User::ROLE_TEACHER
      role_desc = 'Profesor'
    when User::ROLE_ADMIN
      role_desc = 'Admin'
    end
  end
  
  def student?
    self.role == User::ROLE_STUDENT
  end
  
  def teacher?
    self.role == User::ROLE_TEACHER
  end
  
  def admin?
    self.role == User::ROLE_ADMIN
  end
  
  def create_from_facebook(facebook_data)
    #facebook_data_array = JSON.parse(facebook_data)
    if !User.exists?(:email => facebook_data["email"])
      puts "no user with that email"
      self.email = facebook_data["email"]
      self.password = '123456'
      self.password_confirmation = '123456'
      self.name = facebook_data["name"]
      self.facebook_id = facebook_data["id"]
      self.save
    else
      user = User.find_by_email(facebook_data["email"])
      if user.facebook_id == 0
        user.facebook_id = facebook_data["id"]
        user.save
      end 
    end
    
  end
  
  private

  def default_values
    self.role ||= User::ROLE_STUDENT
  end 
  
  def create_role
    id = self.id 

      if self.role == User::ROLE_STUDENT
        insert_sql = "insert into quiero_aprender.students (id) values (#{id})"
      elsif self.role == User::ROLE_TEACHER
        insert_sql = "insert into quiero_aprender.teachers (id) values (#{id})"
      end

      if insert_sql
        ActiveRecord::Base.connection.execute insert_sql
      end
  end
  
end

app/controllers/user_controller.rb
require 'koala'

class UserController < ApplicationController
  def index

  end

  def facebook_login
    if params[:code]
      # acknowledge code and get access token from FB
      session[:access_token] = session[:oauth].get_access_token(params[:code])
    end

    # auth established, now do a graph call:
    @api = Koala::Facebook::API.new(session[:access_token])

    begin
      @user_profile = @api.get_object("me")
    rescue Exception=>ex
      puts ex.message
      #if user is not logged in and an exception is caught, redirect to the page where logging in is requested
      redirect_to '/user/facebook_authorization' and return
    end

    respond_to do |format|
      format.html {   }
    end
  end

  def facebook_authorization
    session[:oauth] = Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::SECRET, Facebook::SITE_URL)
    @auth_url =  session[:oauth].url_for_oauth_code(:permissions=>"read_stream publish_stream")

    redirect_to @auth_url
  end

  def show
	@user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource
  before_action :set_user, :only => [:show, :edit, :update, :destroy]
  before_filter :require_user, :only => [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
	    #id = @user.id	

	    #if user_params[:role].to_i == User::ROLE_STUDENT
		  #  insert_sql = "insert into quiero_aprender.students (id) values (#{id})"
      #elsif user_params[:role].to_i == User::ROLE_TEACHER
		  #  insert_sql = "insert into quiero_aprender.teachers (id) values (#{id})"
      #end

	    #if insert_sql
	     # ActiveRecord::Base.connection.execute insert_sql
	    #end
	    flash[:notice] = "Tu cuenta ha sido creada"
   	  redirect_to :root
    else
	    flash[:notice] = "Hubo un error al intentar crear la cuenta"
	    render :action => :new
    end
    # Saving without session maintenance to skip
    # auto-login which can't happen here because
    # the User has not yet been activated
    

  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(user_params)
      flash[:notice] = "Account updated!"
      redirect_to home_url
    else
      render :action => :edit
    end
  end
  
  def new_teacher
    @user = User.new
    @user.role = User::ROLE_TEACHER
  end
  
  def create_teacher
    @user = User.new(user_params)
    @user.role = User::ROLE_TEACHER
    if @user.save
      id = @user.id 

      #if user_params[:role].to_i == User::ROLE_STUDENT
       # insert_sql = "insert into quiero_aprender.students (id) values (#{id})"
      #elsif user_params[:role].to_i == User::ROLE_TEACHER
       # insert_sql = "insert into quiero_aprender.teachers (id) values (#{id})"
      #end

      #if insert_sql
       # ActiveRecord::Base.connection.execute insert_sql
      #end
      flash[:notice] = "Tu cuenta de profesor ha sido creada exitosamente"
      url = "/teachers/#{id}"
      redirect_to url
    else
      flash[:notice] = "Ha ocurrido un error al intentar crear el profesor"
      render :action => :create_teacher
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :description, :birthdate, :image)
    end
  
  #def show
  #  @user = User.find(params[:id])
  #end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :url => users_path do |f| %>

	<div class="row">
		<div class="col-md-4">
	  		<%= f.label :email %>
		</div>
	  <div class="col-md-6">
	  	<%= f.text_field :email, :class => 'form-control', :placeholder => @user.email %>
	  </div>
	</div>
	<div class="row">
		<div class="col-md-4">
	  		<b>Nombre</b>
		</div>
	  <div class="col-md-6">
	  	<%= f.text_field :name, :class => 'form-control', :placeholder => @user.name %>
	  </div>
	</div>
	<div class="row">
		<div class="col-md-4">
	  		<b>Descripción para mostrar</b>
		</div>
	  <div class="col-md-6">
	  	<%= f.text_field :description, :class => 'form-control', :placeholder => @user.description %>
	  </div>
	</div>
	<div class="row">
		<div class="col-md-4">
	  		<b>Fecha de nacimiento</b>
		</div>
	  <div class="col-md-6">
		<%= f.text_field :birthdate, :id => "datepicker", :value => Date.today %>
	  </div>
	</div>
	<script>
	$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
	</script>
	<div class="row">
		<div class="col-md-4">
		  	<%= f.label :password %>
	  	</div>
	  <div class="col-md-6">
	  	<%= f.password_field :password, :class => 'form-control', :placeholder => '' %>
	  </div>
	</div>
	<div class="row">
	  	<div class="col-md-4">
		  	<%= f.label :password_confirmation %>
	  	</div>
	  <div class="col-md-6">
	  	<%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => '' %>
	  </div>
	</div>
	
	<div class="row">
		<div class="col-md-4">
	    	<%= f.label :role %>
		</div>
  	<div class="col-md-6">
	    <%= f.select :role, [["Estudiante", User::ROLE_STUDENT], ["Profesor", User::ROLE_TEACHER], ["Admin", User::ROLE_ADMIN]], {}, { :class => 'selectpicker', 'data-style' => "btn-primary"} %>
	</div>
	

	<div class="actions col-md-4">
		<% if !defined? @submit_text then @submit_text = 'Save' end%>
		<%= f.submit @submit_text, :class => 'btn btn-primary' %>
		<% if defined? @back_link %>
			<%= link_to 'Back', @back_link, {:class => 'btn btn-primary'} %>
		<% end %>
	</div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for @user, method: :patch  do |f| %>

	<div class="row">
		<div class="col-md-4">
	  		<b>Nombre</b>
		</div>
	  <div class="col-md-6">
	  	<%= f.text_field :name, :class => 'form-control', :placeholder => @user.name %>
	  </div>
	</div>
	<div class="row">
		<div class="col-md-4">
	  		<b>Descripción para mostrar</b>
		</div>
	  <div class="col-md-6">
	  	<%= f.text_field :description, :class => 'form-control', :placeholder => @user.description %>
	  </div>
	</div>	
	<div class="row">
		<div class="col-md-4">
	  		<b>Imagen</b>
		</div>
	  <div class="col-md-6">
	  	<%= f.text_field :image, :class => 'form-control', :placeholder => @user.image %>
	  </div>
	</div>	
	<div class="row">
		<div class="col-md-4">
	  		<b>Fecha de nacimiento</b>
		</div>
	  <div class="col-md-6">
		<%= f.text_field :birthdate, :id => "datepicker", :value => @user.birthdate %>
	  </div>
	</div>
	<script>
	$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
	</script>

	<div class="actions col-md-4">
		<% if !defined? @submit_text then @submit_text = 'Save' end%>
		<%= f.submit @submit_text, :class => 'btn btn-primary' %>
		<% if defined? @back_link %>
			<%= link_to 'Back', @back_link, {:class => 'btn btn-primary'} %>
		<% end %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit col-md-8">
	<div class="page-header">
  		<h2>Edit User</h2>
	</div>
	<%= render 'form_edit' %>

</div>

app/views/users/new.html.erb
<div class="user-edit col-md-8">
	<div class="page-header">
  		<h2>Add New User</h2>
	</div>
	<%= render 'form' %>
</div>

app/views/users/new_teacher.html.erb
<div class="user-edit col-md-8 teacherCreation">
	<div class="page-header">
  		<h2>Registracion</h2>
	</div>

	<%= form_for @user, :url => create_teacher_path do |f| %>
	
		<div class="row">
			<div class="col-md-3">
		  		<%= f.label :email %>
			</div>
		  <div class="col-md-4">
		  	<%= f.text_field :email, :class => 'form-control', :placeholder => @user.email %>
		  </div>
		</div>
		
		<div class="row">
			<div class="col-md-3">
		  		<b>Nombre</b>
			</div>
		  <div class="col-md-4">
		  	<%= f.text_field :name, :class => 'form-control', :placeholder => @user.name %>
		  </div>
		</div>
		<div class="row">
			<div class="col-md-3">
		  		<b>Descripción para mostrar</b>
			</div>
		  <div class="col-md-4">
		  	<%= f.text_field :description, :class => 'form-control', :placeholder => @user.description %>
		  </div>
		</div>
		<div class="row">
			<div class="col-md-3">
		  		<b>Fecha de nacimiento</b>
			</div>
		  <div class="col-md-4">
			<%= f.text_field :birthdate, :id => "datepicker", :class => 'form-control', :value => Date.today %>
		  </div>
		</div>
		<script>
		$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
		</script>
		<div class="row">
			<div class="col-md-3">
			  	<b>Password</b>
		  	</div>
		  <div class="col-md-4">
		  	<%= f.password_field :password, :class => 'form-control', :placeholder => '' %>
		  </div>
		</div>
		<div class="row">
		  	<div class="col-md-3">
			  	<b>Confirma tu Password</b>
		  	</div>
		  <div class="col-md-4">
		  	<%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => '' %>
		  </div>
		</div>
	
		<div class="actions col-md-4">
			<% if !defined? @submit_text then @submit_text = 'Crear' end%>
			<%= f.submit @submit_text, :class => 'btn btn-primary' %>
			<% if defined? @back_link %>
				<%= link_to 'Back', @back_link, {:class => 'btn btn-primary'} %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<html>
<head>
<style>
div.ex {
    width: 700px;
    height: 500px;
    padding 10px;
    border: 2px solid gray;
    margin: 0px;
}
</style>
</head>
<body>


	<div class="row">
		<div class="col-md-4">

			<br><br>

			<p>
				<font size = 6><b> <%= @user.name %> </b></font>
			</p>

			<br>
            			<img src= "<%= @user.image %>" width="400" height="200" alt="..." />
			<br><br>
	
			<p>
				<b> Email: <%= @user.email %></b>
			</p>
		</div>
</body>
</html>