config/routes.rb
QuieroAprender::Application.routes.draw do
  
  resources :welcome
    
  resources :user_sessions
    match 'login' => "user_sessions#new",  :as => :login, via: [:get, :post]
    match 'logout' => "user_sessions#destroy", :as => :logout, via: [:get, :post]

  resources :user_facebook_sessions
    match 'fb_login' => "user_facebook_sessions#login", :as => :fb_login, via: [:get, :post]
    match 'fb_authorization' => "user_facebook_sessions#authorization", :as => :fb_authorization, via: [:get, :post]
    match 'fb_authorization_callback' => "user_facebook_sessions#authorization_callback", :as => :fb_authorization_callbak, via: [:get, :post]
    match 'fb_publish_wall_post' => "user_facebook_sessions#publish_wall_post", :as => :fb_publish_wall_post, via: [:get, :post]
    match 'fb_logout' => "user_facebook_sessions#logout", :as => :fb_logout, via: [:get, :post]
    
  resources :users  # give us our some normal resource routes for users
    match 'signup' => 'users#new', :as => :signup, via: [:get, :post]
    match '/users/edit/:id' => 'users#edit', :as => :update, via: [:get, :post]
    match 'createTeacher' => 'users#create_teacher', :as => :create_teacher, via: [:get, :post]
    match 'newTeacher' => 'users#new_teacher', :as => :new_teacher, via: [:get, :post]
  
  resources :plans
    match 'plans' => "plans#index", :as => :plans_index, via: [:get, :post]
    match 'plans/:id' => "plans#show", :as => :plans_show, via: [:get, :post]
  
  resources :teachers
    match 'home' => "welcome#index", :as => :home, via: [:get, :post]
  
  get '/update_subcategories' => "welcome#update_subcategories", as: 'update_subcategories'

  get '/decode_address' => "welcome#decode_address", as: 'decode_address'
  get '/courses/update_subcategories_courses' , as: 'update_subcategories_courses'
  get '/courses/enroll/:id', to: 'courses#enroll', as: 'enroll_course'
  get '/uploads/:id', to: 'uploads#index', as: 'upload'
  resources :courses do
    resources :opinions, :only => [:create]
    resources :consultations, :only => [:create]
    resources :uploads, :only => [:create]
  end
  resources :advertisings
  resources :students
  

  root :to => "welcome#index"

end

app/models/teacher.rb
class Teacher < User
	has_many :course_teachers
	has_many :courses, :through => :course_teachers
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  authorize_resource
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
	@teacher = Teacher.find(params[:id])
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :description)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h2>Perfil</h2>
<br><br>

	<div class="container">
		<div class="row">
			<div class="col-md-6">
		  
		    <!--div class="panel panel-default"-->
					<!--div class="panel-body"-->
		            		<div class="row">
		                      <div class="col-xs-12 col-sm-4 text-center">
		                              <img src="http://sp0.fotolog.com/photo/32/23/87/kapanga_a_muerte/1237044707429_f.jpg" alt="" class="center-block img-circle img-responsive">
		                              <ul class="list-inline ratings text-center" title="Ratings">
		                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
		                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
		                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
		                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
		                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
		                              </ul>
		                      </div><!--/col-->
		                      <div class="col-xs-12 col-sm-8">
		                          <h2><%= @teachers.find_by_id(1).name %></h2>
		                          <p><strong>Descripción: </strong> <%= @teachers.find_by_id(1).description %> </p>
		                          <p><strong>Hobbies: </strong> Amo la música, los animales y el fútbol</p>
		                          <p><strong>Géneros: </strong>
		                              <span class="label label-info tags">Rock</span> 
		                              <span class="label label-info tags">Tango</span>
		                              <span class="label label-info tags">Clásicos</span>
		                              <span class="label label-info tags">Nacional</span>
		                          </p>
		                      </div><!--/col-->
										</div><!--row-->
										<div class="row">
		                	<div class="col-xs-12 col-sm-4">
												<center>		                          
													<h2><strong> 240 </strong></h2>                    
		                      <h2><p> Alumnos </p></h2>
		                      <button class="btn btn-success btn-block">
														<span class="fa fa-user"/> Ver alumnos 
													</button>
												</center>
		                  </div><!--/col-->
		                  <div class="col-xs-12 col-sm-4">
												<center>
		                    	<h2><strong><center> 4 </center></strong></h2>                    
		                     	<h2><p> Cursos </p></h2>
		                     	<button class="btn btn-info btn-block">
														<span class="fa fa-university"/> Ver Cursos 
													</button>
												</center>
		                  </div><!--/col-->
		                  <div class="col-xs-12 col-sm-4">
												<center>
		                     	<h2><strong><center> 17 </center></strong></h2>                    
		                     	<h2><p> Recomendaciones </p></h2>
		                     	<button type="button" class="btn btn-primary btn-block">
														<span class="fa fa-thumbs-up"/> Recomendar
													</button>
												</center>  
		                	</div><!--/col-->
		            		</div><!--/row-->
		            <!--/div--><!--/panel-body-->
		        <!--/div--><!--/panel-->
 
		  </div><!--/col-->
		</div><!--/row-->
	</div><!--container-->

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<div class="row">
	<br>
	<div class="col-md-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
			   <b><%= @teacher.name %></b>
			</div>
			<div class="panel-body">
				<% if @teacher.image %>
					<%= image_tag "profiles/#{@teacher.image}", :style => "margin-bottom: 20px" %>
				<% end %>
				<% if @teacher.birthdate %>
					<p><b>Fecha de nacimiento:</b> <%= @teacher.birthdate.strftime("%d/%m/%Y") %></p>
				<% end %>
			   <p><b>Email:</b> <%= @teacher.email %></p>
			   <p><b>Descripción:</b> <%= @teacher.description %></p>
			   <!-- <img src= "<%= @teacher.image %>" width="400" height="200" alt="..." /> -->
			</div>
		</div>

		<%= button_to 'Nuevo Curso', new_course_path , class: "btn btn-primary btn-lg center-block", :method => :get %>

	</div>

	<div class="col-md-9">
		<h1>Cursos dictados</h1>
		<table class="table table-bordered table-hover table-condensed">
		  <thead class="courseList">
		    <tr>
		      <th>Nombre </th>
		      <th>Descripción </th>
		      <th>Precio</th>      
		      <th>Opciones</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @teacher.courses.each do |course| %>
		      <tr>
		        <td ><%= course.name %></td>
		        <td><%= course.description %></td>
		        <td class="text-center"><%= course.price %></td>
		        <td class="text-center">
		          <%= button_to course , class: "btn btn-primary btn-xs", :method => :get do %>
		            <span class="glyphicon glyphicon-eye-open "></span>
		          <% end %>
		          <%= button_to edit_course_path(course) , class: "btn btn-primary btn-xs", :method => :get do %>
		            <span class="glyphicon glyphicon-edit"></span>
		          <% end %>
		          <%= button_to course ,class: "btn btn-danger btn-xs", method: :delete, data: {confirm: 'Are you sure?' } do %>
		          <span class="glyphicon glyphicon-remove"></span>
		          <% end %>
		         	<button type="button" data-toggle="modal" data-target="#myModal" id="estadisticas_<%= course.id %>" class="btn btn-xs btn-success">Estadísticas</button>
		        </td>  
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>