config/routes.rb
QuieroAprender::Application.routes.draw do
  
  resources :welcome
    
  resources :user_sessions
    match 'login' => "user_sessions#new",  :as => :login, via: [:get, :post]
    match 'logout' => "user_sessions#destroy", :as => :logout, via: [:get, :post]

  resources :user_facebook_sessions
    match 'fb_login' => "user_facebook_sessions#login", :as => :fb_login, via: [:get, :post]
    match 'fb_authorization' => "user_facebook_sessions#authorization", :as => :fb_authorization, via: [:get, :post]
    match 'fb_authorization_callback' => "user_facebook_sessions#authorization_callback", :as => :fb_authorization_callbak, via: [:get, :post]
    match 'fb_publish_wall_post' => "user_facebook_sessions#publish_wall_post", :as => :fb_publish_wall_post, via: [:get, :post]
    match 'fb_logout' => "user_facebook_sessions#logout", :as => :fb_logout, via: [:get, :post]
    
  resources :users  # give us our some normal resource routes for users
    match 'signup' => 'users#new', :as => :signup, via: [:get, :post]
    match '/users/edit/:id' => 'users#edit', :as => :update, via: [:get, :post]
    match 'createTeacher' => 'users#create_teacher', :as => :create_teacher, via: [:get, :post]
    match 'newTeacher' => 'users#new_teacher', :as => :new_teacher, via: [:get, :post]
  
  resources :plans
    match 'plans' => "plans#index", :as => :plans_index, via: [:get, :post]
    match 'plans/:id' => "plans#show", :as => :plans_show, via: [:get, :post]
  
  resources :teachers
    match 'home' => "welcome#index", :as => :home, via: [:get, :post]
  
  get '/update_subcategories' => "welcome#update_subcategories", as: 'update_subcategories'

  get '/decode_address' => "welcome#decode_address", as: 'decode_address'
  get '/courses/update_subcategories_courses' , as: 'update_subcategories_courses'
  get '/courses/enroll/:id', to: 'courses#enroll', as: 'enroll_course'
  get '/uploads/:id', to: 'uploads#index', as: 'upload'
  resources :courses do
    resources :opinions, :only => [:create]
    resources :consultations, :only => [:create]
    resources :uploads, :only => [:create]
  end
  resources :advertisings
  resources :students
  

  root :to => "welcome#index"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  puts "al"
  authorize_resource
  puts "lo"
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_filter :require_user, :only => :new
  #examples
  #before_filter :require_user, :all
  #before_filter :require_user, :except => [:show, :index]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
   @course = Course.find(params[:id])
   @advertisings = []
   getAdvertising(@course, @advertisings)
   @cursosRelacionados = []
   getCursosRelacionados(@course, @cursosRelacionados)
   @opinion = Opinion.new
   @consultation = Consultation.new
   @rating_average = @course.get_rating_average
  end

  def getAdvertising(course, advertisings)
  #  @course.tags.each do |t|
      @advertisings = Advertising.all   
  #  end
  end 

  def getCursosRelacionados(course, cursosRelacionados) 
    Course.all.each do |c|
      if(c.id != course.id)
        @cursosRelacionados << c
       end 
    end 
  end  

  # GET /courses/new
  def new
    @course = Course.new
    @categories = Category.all
    @subcategories = Category.find(1).subcategories
    @posibleTags=Tag.all.map{|a| a.name}
    @selectedTags=[]
  end

  # GET /courses/update_subcategories_courses
  def update_subcategories_courses
    category = Category.find(params[:category_id])
    @subcategories = category.subcategories.map{|a| [a.name, a.id]}
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    @categories = Category.all
    @subcategories = Category.find(1).subcategories
    @posibleTags=Tag.all.map{|a| a.name}
    @selectedTags= []
  end

  # GET /courses/enroll
  def enroll
    @course = Course.find(params[:id])
    if(current_user && (current_user.role == User::ROLE_STUDENT)) 
       @courseStudent = CourseStudent.new(:course_id => @course.id, :student_id => current_user.id) 
       @courseStudent.save
       flash[:info] = "Se inscribio correctamente!"
       session["courseId"] = nil 
    else
      flash[:error] = "Debe ser un estudiante logueado para inscribirse"
      session["courseId"] = params[:id]
    end 
    redirect_to @course
  end  

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    setTags(@course)
    respond_to do |format|
      if @course.save
        if(current_user && current_user.role == User::ROLE_TEACHER) 
           @courseTeacher = CourseTeacher.new(:course_id => @course.id, :teacher_id => current_user.id) 
           @courseTeacher.save
        end   
        format.html { redirect_to @course, notice: 'El curso se creo exitosamente.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def setTags(course)
    params[:selectedTags].gsub!(/\s/,'')
    tags = params[:selectedTags].split(',')
    tags.each do |t|
    tag = Tag.find_by_name(t)
      @course.tags << tag
    end 
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @course = Course.find(params[:id])
    setTags(@course)
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
   # Use callbacks to share common setup or constraints between actions.
    def set_course
 #     @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :longitude, :latitude, :address, :subcategory_id, :price, :tags, :opinions, :consultations,:uploads)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper

	def is_friends_have_taken_a_course(course)
		friends_count = rand(4);
	end

	def string_count_of_friends_taken_a_course
		friends_count = 1 + rand(3)
		if friends_count == 1 then
			return "Un amigo ha realizado este curso"
		end
		if friends_count > 1 then
			return "#{friends_count} amigos han realizado este curso"
		end
	end

end

app/views/courses/_form.html.erb
<%= bootstrap_form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row ">
    <div class="col-md-4 ">  
      <div class="field" >
         <%= f.text_field :name, :required => true , :label => "Nombre del curso", :placeholder => "Nombre" %>
      </div>
    </div>
  </div> 
  <br>
  <div class="row">
    <div class="col-md-4 ">     
      <div class="field">
        <%= f.text_area :description, :label => "Descripción", :placeholder => "Descripción" %>
      </div>
    </div>
    <div class="col-md-4">  
      <%= f.text_field :address, :required => true , :label => "Dirección", :placeholder => "Dirección" ,:class => "required" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-2 ">
      <p class="control-label" >Categoría</p>
          <select id="category-select" class="form-control" >
              <%= options_from_collection_for_select(@categories, 'id', 'name') %>
          </select>
  
    </div>
    <div class="col-md-2">
       <%= f.collection_select(:subcategory_id, @subcategories, :id, :name, {:prompt   => "Seleccione una opción"}, {:id => 'subcategory-select' , :required => true } ) %>
    </div>

    <div class="col-md-4">
     <p class="control-label">Tags</p>
     <input type="text" class="form-control" id="tokenfield" name="selectedTags" value="<%= @course.tags.map{|a| a.name}.join(",") %>" />
    </div>
  </div>
  <div class="row">
  <div class="col-md-4">  
      <%= f.text_field :price, :label => "Precio", :placeholder => "Precio" %>
    </div>
  </div>  
  <hr>
  <hr>

  <div class="col-md-4">
    <button type="submit" class="btn btn-primary">Crear</button>
  
  
  
<% end %>

<script type="text/javascript" >
    $('#category-select').change(function() {
      $.ajax({
        url:  "<%= update_subcategories_courses_path %>",
        data: {
          category_id : $('#category-select').val()
        },
        dataType: "script"
      });
    });
    $('#tokenfield').tokenfield({
        autocomplete: {
          source: <%= raw @posibleTags %>,
          delay: 100
        },
        showAutocompleteOnFocus: true
    });
</script>

app/views/courses/edit.html.erb
<h3><%= @course.name %> </h3>

<hr>
<%= render 'form' %>

<%= button_to 'Ver', @course , class: "btn btn-primary" , :method => :get %> 
<%= button_to 'Volver',courses_path , class: "btn btn-primary" , :method => :get %>
<hr>

<%= javascript_tag do %>

var addressPicker = new AddressPicker();
$('#course_address').typeahead(null, {
  displayKey: 'description',
  source: addressPicker.ttAdapter()
});
 
$(addressPicker).on('addresspicker:selected', function (event, result) {
  $('#your_lat_input').val(result.lat());
  $('#your_lng_input').val(result.lng());
  $('#your_city_input').val(result.nameForType('locality'));
});

<% end %>

app/views/courses/index.html.erb
<h1>Cursos</h1>

<hr>
<table class="table table-bordered table-hover table-condensed">
  <thead class="courseList">
    <tr>
      <th>Nombre </th>
      <th>Descripción </th>
      <th>Dirección </th>
      <th>Precio</th>      
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.address %></td>
        <td><%= course.price %></td>
        <td>
          <%= button_to course , class: "btn btn-primary btn-xs", :method => :get do %>
            <span class="glyphicon glyphicon-eye-open "></span>
          <% end %>
          <%= button_to edit_course_path(course) , class: "btn btn-primary btn-xs", :method => :get do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= button_to course ,class: "btn btn-danger btn-xs", method: :delete, data: {confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-remove"></span>
          <% end %>
         
        </td>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<hr>

app/views/courses/new.html.erb
<hr>
<hr>
<hr>
<h1>Crear curso</h1>
<hr>
<%= render 'form' %>

<%= button_to 'Volver',courses_path , class: "btn btn-primary" , :method => :get %>

</div>



<hr>


<%= javascript_tag do %>
var addressPicker = new AddressPicker();
$('#course_address').typeahead(null, {
  displayKey: 'description',
  source: addressPicker.ttAdapter()
});
 
$(addressPicker).on('addresspicker:selected', function (event, result) {
  $('#your_lat_input').val(result.lat());
  $('#your_lng_input').val(result.lng());
  $('#your_city_input').val(result.nameForType('locality'));
});

<% end %>

app/views/courses/show.html.erb
<% content_for :head do %>
	<!-- Open Graph Metadata -->
	<meta property="fb:app_id" content=<%= Facebook::APP_ID%> />
	<meta property="og:title" content="<%= "Quiero Aprender - " + @course.name %>" />
	<meta property="og:site_name" content="Quiero Aprender" />
	<!--meta property="og:type" content="website" /-->
	<meta property="og:url" content="<%= request.original_url %>" />
	<meta property="og:image" content="http://sndt.ac.in/images/courses/courses-imgs.jpg" />
	<meta property="og:description" content="<%= @course.description %>" />
<% end %>

<style>
  #course_map {
     display: block;
     height: 300px;
     width: 100%;
  }
</style>

<!-- Carousel Photo Gallery Script -->
<script type="text/javascript" >
  $( document ).ready(function() {
      $('.carousel').carousel();
});
</script>

<!-- Toque algo en bootstrap que hace que se vean feas las estrellas, asi que lo incluyo
de vuelta para que se vean lindas pisando la config que toque arriba :P 
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
-->
<div class="row">
	<div class="col-md-4">
		<hr>
		<div id="myCarousel" class="carousel slide">
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<% if(@course.uploads.size() > 0) %>
				<div class="item active">
					<img src="<%= @course.uploads.first().upload %>" style="width:400px;height:300px;" />
					<div class="carousel-caption"><%= @course.name %></div>
				</div>
				<% @course.uploads.drop(1).each do |u| %>
					<div class="item ">
							<img src="<%= u.upload %>" style="width:400px;height:300px;" />
							<div class="carousel-caption"><%= @course.name %></div>
					</div>
				<% end %>
				<% else %>
					<div class="item active">
					<%= image_tag "college.png" , :size=>"300x400" %>
						<div class="carousel-caption"><%= @course.name %></div>
					</div>
				<% end %> 	
			</div>
			<!-- Carousel nav -->
			<a class="carousel-control left" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
			<a class="carousel-control right" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
		</div>
		<% if is_logued_teacher? %>
			<%= button_to 'Imagenes', upload_path(@course), class:"btn btn-primary", :method => :get %>
		<% end %>
	</div>
	<div class="col-md-5">
		<h1><%= @course.name %></h1>
		<% if is_logued_student_with_facebook_id? and (is_friends_have_taken_a_course(@course) > 0) %>
		<h5 style="font-family:Helvetica; color:#3B5998"><%= string_count_of_friends_taken_a_course %></h5>
		<% end%>
		<button role="button" class="btn btn-social btn-facebook" data-toggle="modal" data-target="#FbShareModal"><i class="fa fa-facebook"></i> | Compartir en Facebook</button>
		<!-- Facebook share modal view -->
		<div class="modal fade" id="FbShareModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<%= bootstrap_form_tag url:fb_publish_wall_post_path do |f| %>
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
						</button>
						<h4 class="modal-title" id="myModalLabel">Comparte el curso con tus amigos de Facebook!</h4>
					</div>
					<div class="modal-body">
						<%= f.text_area 'message', value: 'Voy a hacer este curso, va a ser fantástico!', size: '10x8', hide_label: true%>
						<%= f.hidden_field 'attachment[name]', value:@course.name + ' - Quiero Aprender' %>
						<%= f.hidden_field 'attachment[link]', value:request.original_url %>
						<%= f.hidden_field 'attachment[description]', value:@course.description %>
						<%= f.hidden_field 'attachment[picture]', value:"http://sndt.ac.in/images/courses/courses-imgs.jpg" %>
					</div>
					<div class="modal-footer">
						<%= f.submit "Publicar", class: "btn btn-primary" %>
					</div>
				</div>
				<% end %> <!-- End Facebook share form -->
			</div>
		</div>
		<!-- End Facebook share modal view-->

		<hr>
		<p>
			<b>Descripción:</b> <%= @course.description %>
		</p>
		<p>
			<b>Dirección:</b> <%= @course.address %>
		</p>
		<p>
			<b>Subcategoría:</b>
			<% if (@course.subcategory != nil) %>
			<%= h @course.subcategory.name %>
		</p>
		<p>
			<b>Precio:</b> <span class="glyphicon glyphicon-usd"></span> <%= @course.price %>
		</p>
		<p>
			<b>Características:</b>
			<% @course.tags.each do |t| %>
				<%= t.name %>
			<% end %>
		</p>

		<div class="row">
			<div class="col-xs-4 ">
				<div class="basic" data-average="12" data-id="1"></div>
				<%= button_to 'Inscribirme!' , enroll_course_path(@course) , class: "btn btn-lg btn-success" , :method => :get  %>
			</div>			

			<div class="col-xs-3 ">
				<h4><b>Reviews: </b><%= Opinion.where("course_id = ?", @course.id).count	%></h4>
			</div>

			<div class="col-xs-5 ">
				<input id="course_rating" type="number" class="rating" min=0 max=5 readonly="true" data-container-class='text-right' value="<%= @rating_average %>" data-size='sm' >
			</div>

		</div>

	</div>
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-body" id ="cursosRelacionados">
				<h4>Cursos que podrían interesarte </h4>
				<div class="list-group container-results" id="cursosRelacionados">
					<% @cursosRelacionados.each do |c| %>
					<a id="cursosRelacionados_<%= c.id %>" class="list-group-item list-group-item-info" href="/courses/<%= c.id %>" > <h4 class="list-group-item-heading"> <%= c.name %> </h4>
					<p class="list-group-item-text">
						<%= c.description %>
					</p> </a>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-1">
		<div class="panel panel-default container-opinions">
			<ul class="nav nav-tabs nav-justified" id="myTab">
				<li class="active">
					<a href="#Reseñas" data-toggle="tab">Reseñas</a>
				</li>
				<li>
					<a href="#Consultas" data-toggle="tab">Consultas</a>
				</li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane fade in active" id="Reseñas">
					<%= bootstrap_form_for [@course, Opinion.new] do |f| %>
					<div class="panel-body container-opinionsResults" id ="listasReseñas">
						<ul class="media-list ">
							<% @course.opinions.select{|op| not op.user.nil?}.each do |o| %>
							<li class="media">
								<div class="media-body">
									<h5 class="media-heading">
									
									<a class="pull-left opinionProfileImage" href="#">
										<%= image_tag (get_profile_picture_for_user o.user) , :size=>"64x64" %></a>
									
									<b><%= o.user.name %></b>
									<%= o.date.strftime("%m/%d/%Y %H:%M:%S") %>
									</h5>
									<%= o.description %>
									<input id="opinion_<%= o.id %>" type="number" class="rating" min=0 max=5 readonly="true" data-container-class='text-right' value="<%= o.rating.nil? ? 0 : o.rating%>" data-size='xs' >
								</div>
							</li>
							<% end %>
						</ul>
					
					<% if current_user %>
						<div class="col-md-12 col-ms-offset-1" >
							<a id="newOpinion" class="list-group-item " > <h4 class="list-group-item-heading"> Contanos que te gustó del curso </h4>
							<p class="list-group-item-text">
								<textarea class="form-control" id="opinion_description" name="opinion[description]" placeholder="Descripción"></textarea>
								<br>
								<input id="opinion_rating" name="opinion[rating]" value="0" type="number" class="rating" min=0 max=5 step=1 data-size="xs" >
								<button id="addOpinion" class="btn btn-primary col-md-offset-11" >
									Agregar
								</button>

							</p> </a>

						</div>
					<% end %>
					<% end %>
					</div>
				</div>
				<div class="tab-pane fade" id="Consultas">

					<%= bootstrap_form_for [@course, Consultation.new] do |f| %>
					<div class="panel-body container-opinionsResults" id ="listaConsultas">
						<ul class="media-list ">
							<% @course.consultations.select{|consulta| not consulta.user.nil?}.each do |c| %>
							<% if(c.user.role == User::ROLE_TEACHER)  %>
								<li class="media list-group-item-success">
							<% else %>
							<li class="media">
								<% end %>
								<div class="media-body">
									<h5 class="media-heading"> 
									<% unless c.user.nil? %>
									<a class="pull-left opinionProfileImage" href="#">
									<%= image_tag (get_profile_picture_for_user c.user) , :size=>"64x64" %></a>
									<b><%= c.user.name %></b>
									<% end %>
									<%= c.date.strftime("%m/%d/%Y %H:%M:%S") %>
									</h5>
									<%= c.description %>
								</div>
							</li>
							<% end %>
						</ul>
				<% if current_user %>		
					<div class="col-md-12 col-ms-offset-1" >
						<a id="newOpinion" class="list-group-item " > <h4 class="list-group-item-heading"> Preguntas </h4>
						<p class="list-group-item-text">
							<textarea class="form-control" id="consultation_description" name="consultation[description]" placeholder="Descripción"></textarea>
							<br>
							<button id="addOpinion" class="btn btn-primary col-md-offset-11" >
								Agregar
							</button>

						</p> </a>
					</div>
				<% end %>	
					</div>
					<% end %>
				</div>

			</div>
		</div>
	</div>
	<div class="col-md-3 ">
		<div class="panel panel-default">
			<div class="panel-body" id ="cursosRelacionados">
				<h4>Te recomendamos</h4>
				<div class="list-group container-results" id="cursosRelacionados">
					<% @advertisings.each do |a| %>
					<a id="advertising_<%= a.id %>" class="list-group-item list-group-item-success" href="/advertisings/<%= a.id %>" > <h4 class="list-group-item-heading"> <%= a.name %> </h4>
					<p class="list-group-item-text">
						<%= a.description %>
					</p> </a>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<% end %>

<% if is_logued_teacher? %>
<%= button_to 'Editar', edit_course_path(@course) , class: "btn btn-primary" , :method => :get %>
<% end %>	
<%= button_to 'Volver',courses_path , class: "btn btn-primary" , :method => :get %>
<hr>

<%= javascript_tag do %>
	var ready;
	ready = function() {
	<% @course.opinions.each do |o| %>
	    $('#opinion_<%= o.id %>').rating('refresh', {showClear: false, showCaption: false});
	<% end %>
	    $('#course_rating').rating('refresh', {showClear: false, showCaption: false});
	};

	$(document).ready(ready);
	$(document).on('page:load', ready);
<% end %>  

app/views/courses/update_subcategories_courses.js.erb
$('#subcategory-select').html("<%= escape_javascript(options_for_select(@subcategories)) %>");
$('.selectpicker').selectpicker('refresh');